import { MigrationInterface, QueryRunner } from "typeorm";

export class ModerationCaseAction1778159630748 implements MigrationInterface {
    name = 'ModerationCaseAction1778159630748'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."rillo_files_file_type_enum" AS ENUM('document', 'receipt', 'photo', 'video', 'audio', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_files_file_category_enum" AS ENUM('personal', 'financial', 'medical', 'administrative', 'other')`);
        await queryRunner.query(`CREATE TABLE "rillo_files" ("id" SERIAL NOT NULL, "file_name" character varying(255) NOT NULL, "original_name" character varying(255) NOT NULL, "file_path" character varying(500) NOT NULL, "file_size" bigint NOT NULL, "mime_type" character varying(100) NOT NULL, "file_type" "public"."rillo_files_file_type_enum" NOT NULL DEFAULT 'other', "file_category" "public"."rillo_files_file_category_enum" NOT NULL DEFAULT 'other', "uploaded_by" uuid, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "public_url" character varying, CONSTRAINT "PK_b37e240c0ec8b6c6153a4cd48e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_users_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_users_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_users_language_enum" AS ENUM('Arabic', 'English')`);
        await queryRunner.query(`CREATE TABLE "rillo_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "phone_no" character varying NOT NULL, "date_of_birth" TIMESTAMP NOT NULL, "gender" "public"."rillo_users_gender_enum" NOT NULL, "user_name" character varying NOT NULL, "password" character varying NOT NULL, "file_id" integer, "display_name" character varying NOT NULL, "bio" character varying, "role" "public"."rillo_users_role_enum" NOT NULL, "status" "public"."rillo_users_status_enum" NOT NULL DEFAULT 'active', "last_seen_at" TIMESTAMP, "language" "public"."rillo_users_language_enum" DEFAULT 'English', "is_delete_account" boolean NOT NULL DEFAULT false, "account_delete_at" TIMESTAMP, "is_show_your_birth_date" boolean NOT NULL DEFAULT false, "is_show_your_location_on_profile" boolean NOT NULL DEFAULT false, "is_disable_private_chats" boolean NOT NULL DEFAULT true, "is_enable_notifications" boolean NOT NULL DEFAULT true, "is_Save_your_activity_on_this_device" boolean NOT NULL DEFAULT false, "isSubscribedUser" boolean DEFAULT false, "is_moderation_user" boolean DEFAULT false, "subscription_end_at" TIMESTAMP, "created_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by" character varying, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_7777c44889122c755a270faa66a" UNIQUE ("email"), CONSTRAINT "UQ_a9634ffb4f8387a1b7d3f6c2daf" UNIQUE ("user_name"), CONSTRAINT "PK_780cf033135bbf91179a2843d92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_users_location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "location" geography(Point,4326) NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "area" character varying, "city" character varying, "state" character varying, "country" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_b1b231c06197816d7086cc43b6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_userlocation_user_id" ON "rillo_users_location" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_userlocation_location" ON "rillo_users_location" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "rillo_subscription_package_benifits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscription_package_id" uuid NOT NULL, "desc" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_2c727cb43fbfe08db69b88dabcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_subscription_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "price" double precision NOT NULL DEFAULT '0', "discountPercentage" double precision DEFAULT '0', "discountPrice" double precision NOT NULL DEFAULT '0', "duration" integer NOT NULL DEFAULT '0', "type" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_21f70b5791143f4bfa4756328a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_delete_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "is_irrelevant_content" boolean NOT NULL DEFAULT false, "is_negative_community" boolean NOT NULL DEFAULT false, "is_no_activity" boolean NOT NULL DEFAULT false, "is_too_time_consuming" boolean NOT NULL DEFAULT false, "is_other" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_af7242dbe942951b62bec397805" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_story_visibility_enum" AS ENUM('Public', 'Followers', 'Only Me')`);
        await queryRunner.query(`CREATE TABLE "rillo_story" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "file_id" integer NOT NULL, "visibility" "public"."rillo_story_visibility_enum" NOT NULL DEFAULT 'Public', "expires_at" TIMESTAMP NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "view_count" integer NOT NULL DEFAULT '0', "like_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_56d7652ff0e8285e75a126c94e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_20421b07932288469f67bc475e" ON "rillo_story" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "rillo_story_like" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "story_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dbde32e91d8ccc66e5658bf115c" UNIQUE ("story_id", "user_id"), CONSTRAINT "PK_d52997be260f91913a08b10bcf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d70c94c8de4fcc75c76627dc7" ON "rillo_story_like" ("story_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_05776324cabb03bab023d7167b" ON "rillo_story_like" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "rillo_story_view" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "story_id" uuid NOT NULL, "viewer_id" uuid NOT NULL, "viewed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_64d57366a26676f1992a1661f18" UNIQUE ("story_id", "viewer_id"), CONSTRAINT "PK_d4f1cd447e12eecda334b15f415" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bfadfaad415d17a770534cb1fb" ON "rillo_story_view" ("story_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8ce692b12a551825561f21532" ON "rillo_story_view" ("viewer_id") `);
        await queryRunner.query(`CREATE TABLE "rillo_stickers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "uploaded_by_user_id" uuid NOT NULL, "file_id" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_e287b8d8d8a93436700e214966e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dcd44ecf97e2a60a58c0442379" ON "rillo_stickers" ("uploaded_by_user_id") `);
        await queryRunner.query(`CREATE TABLE "rillo_user_post_hide" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loggedInUserId" uuid NOT NULL, "targetUserId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "UQ_faabf7275368d7e6c752f7e5742" UNIQUE ("loggedInUserId", "targetUserId"), CONSTRAINT "PK_a1e995564aec1dfeff102afbcb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_poll_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "pollOption" text, "pollCount" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_1fe7381bb9508da5e6228c64510" UNIQUE ("postId", "pollOption"), CONSTRAINT "PK_d434203ed91a9405015f6b6a48a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "fileId" integer NOT NULL, CONSTRAINT "UQ_1b5be67308979ec3113e9a0c255" UNIQUE ("postId", "fileId"), CONSTRAINT "PK_f35a2afa10c76a79cb4e8dabfce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_posts_posttype_enum" AS ENUM('audio', 'location', 'poll', 'link', 'regular', 'camera', 'photo', 'video')`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_posts_visibility_enum" AS ENUM('ghost', 'normal', 'private')`);
        await queryRunner.query(`CREATE TABLE "rillo_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" text, "linkUrl" text, "postType" "public"."rillo_posts_posttype_enum" NOT NULL DEFAULT 'regular', "visibility" "public"."rillo_posts_visibility_enum" NOT NULL DEFAULT 'normal', "locationId" uuid, "userId" uuid NOT NULL, "likeCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "shareCount" integer NOT NULL DEFAULT '0', "originalPostId" uuid, "location" geography(Point,4326), "latitude" double precision, "longitude" double precision, "area" character varying, "city" character varying, "state" character varying, "country" character varying, "isPollComplete" boolean NOT NULL DEFAULT false, "isBoostRunning" boolean NOT NULL DEFAULT false, "boostEndAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_e2d17ce4d5cc6027cd2f671b360" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de071e5e776235cc5dca2eb304" ON "rillo_posts" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "rillo_post_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8895add108bc85cc582bb3f8a09" UNIQUE ("postId", "userId"), CONSTRAINT "PK_27f45b4463b3a08bf8892c0225d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_post_report_criteria_criteria_enum" AS ENUM('TERRORISM', 'HARASSMENT', 'HATE_SPEECH', 'SPAM', 'IMPERSONATION', 'VIOLENCE')`);
        await queryRunner.query(`CREATE TABLE "rillo_post_report_criteria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportId" uuid NOT NULL, "criteria" "public"."rillo_post_report_criteria_criteria_enum" NOT NULL, CONSTRAINT "UQ_ed7a53c8a43830a3fd49754b905" UNIQUE ("reportId", "criteria"), CONSTRAINT "PK_98b3b861cb72fa7b6c1cee43ba9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_poll_votes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "postPollOptionId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_69da181798de9e06fa3e0d61b87" UNIQUE ("postId", "userId"), CONSTRAINT "PK_fe609a2f91b0cde81548bace7e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_views" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4f9e851069a648280c5087c83ca" UNIQUE ("postId", "userId"), CONSTRAINT "PK_cbb3d4e514aea8632bdcae8946b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_pins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d55f55003828bc25181a1679a7b" UNIQUE ("postId", "userId"), CONSTRAINT "PK_d3891aa916f949682b895c8d993" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_51ecc933289d82022bb22c202f5" UNIQUE ("postId", "userId"), CONSTRAINT "PK_7ba7f31a3ca5dafe67b8806ba3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_hide" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_22cd5e9c6c92f7308e333d1d63e" UNIQUE ("postId", "userId"), CONSTRAINT "PK_c68dc80400ee101600b0d438f1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_post_likes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c9de69b26703fde21f30055c20" UNIQUE ("postId", "userId"), CONSTRAINT "PK_ad9a69d3026b229fb78d05e84eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_poll_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "remarks" character varying, "created_by_user_id" uuid NOT NULL, "is_active" boolean DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid, CONSTRAINT "UQ_746c975d74bc37eb7e1f78dd26a" UNIQUE ("name"), CONSTRAINT "PK_00d6f1df7a2cc5b7a6517290b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_subscription_payments_status_enum" AS ENUM('created', 'initiated', 'pending', 'paid', 'failed', 'canceled', 'expired', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "rillo_subscription_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "subscription_package_id" uuid NOT NULL, "status" "public"."rillo_subscription_payments_status_enum" NOT NULL DEFAULT 'created', "provider" character varying(50) NOT NULL DEFAULT 'myfatoorah', "amount" double precision NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'KWD', "myfatoorah_invoice_id" character varying(100), "myfatoorah_payment_id" character varying(255), "myfatoorah_invoice_reference" character varying(255), "gateway_response" jsonb, "webhook_payload" jsonb, "paid_at" TIMESTAMP, "failed_at" TIMESTAMP, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_89c5c0ba27e0a9bf0fc55ff646c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_user_subscriptions_status_enum" AS ENUM('active', 'expired', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "rillo_user_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "subscription_package_id" uuid NOT NULL, "subscription_payment_id" uuid NOT NULL, "status" "public"."rillo_user_subscriptions_status_enum" NOT NULL DEFAULT 'active', "starts_at" TIMESTAMP NOT NULL, "ends_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_d371327a8ff90dbe5c028e2ae0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_user_to_firebase_token_map" ("id" SERIAL NOT NULL, "userId" uuid NOT NULL, "token" character varying(512) NOT NULL, "lastActiveAt" TIMESTAMP, CONSTRAINT "PK_85b7ceb0a0cc2efb5181f65f50e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_payments_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "subscription_package_id" uuid NOT NULL, "is_success" boolean NOT NULL DEFAULT false, "message" character varying(255), "validation_errors" jsonb, "invoice_id" bigint, "invoice_status" character varying(100), "invoice_reference" character varying(255), "customer_reference" character varying(255), "provider_created_at" TIMESTAMP, "expiry_date" date, "expiry_time" character varying(50), "invoice_value" double precision, "comments" text, "customer_name" character varying(255), "customer_mobile" character varying(50), "customer_email" character varying(255), "user_defined_field" character varying(255), "invoice_display_value" character varying(100), "due_deposit" double precision, "deposit_status" character varying(100), "invoice_items" jsonb, "invoice_transactions" jsonb, "suppliers" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_45b03434991c592b36beb4ccf88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_notification_records_deliverystatus_enum" AS ENUM('Delivered', 'Pending')`);
        await queryRunner.query(`CREATE TABLE "rillo_notification_records" ("id" SERIAL NOT NULL, "userId" uuid, "notificationTitle" character varying(255) NOT NULL, "notificationMessage" character varying(255) NOT NULL, "payload" character varying, "deliveryStatus" "public"."rillo_notification_records_deliverystatus_enum" DEFAULT 'Pending', "isSeen" boolean DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_23c5656abdb7edcc66285e5c1e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_moderation_requests_status_enum" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "rillo_moderation_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestedById" uuid NOT NULL, "status" "public"."rillo_moderation_requests_status_enum" NOT NULL DEFAULT 'pending', "message" text, "reviewNote" text, "reviewedById" uuid, "reviewedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_1bd95f3dbfa42626b7db46ad36a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_moderation_actions_actiontype_enum" AS ENUM('claim', 'dismiss', 'escalate', 'hide_post', 'restore_post', 'lock_conversation', 'unlock_conversation')`);
        await queryRunner.query(`CREATE TABLE "rillo_moderation_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "moderatorUserId" uuid NOT NULL, "actionType" "public"."rillo_moderation_actions_actiontype_enum" NOT NULL, "note" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d47c203bd139469f20447c598ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_conversation_participant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "is_admin" boolean NOT NULL DEFAULT false, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_455a4b491423cc55afdc193dfbc" UNIQUE ("conversation_id", "user_id"), CONSTRAINT "PK_e32027f994171f25f0c8f3d8fc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_conversation_type_enum" AS ENUM('direct', 'group')`);
        await queryRunner.query(`CREATE TABLE "rillo_conversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_one_id" uuid, "user_two_id" uuid, "type" "public"."rillo_conversation_type_enum" NOT NULL DEFAULT 'direct', "title" character varying, "image_id" integer, "created_by" uuid, "is_active" boolean NOT NULL DEFAULT true, "is_chat_request_accepted" boolean NOT NULL DEFAULT false, "is_moderation_locked" boolean NOT NULL DEFAULT false, "moderation_locked_by" uuid, "moderation_locked_at" TIMESTAMP, "moderation_lock_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99b49aff048783cf3a2375740cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_moderation_cases_targettype_enum" AS ENUM('post', 'conversation')`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_moderation_cases_status_enum" AS ENUM('open', 'in_review', 'resolved', 'dismissed', 'escalated')`);
        await queryRunner.query(`CREATE TABLE "rillo_moderation_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "targetType" "public"."rillo_moderation_cases_targettype_enum" NOT NULL, "postId" uuid, "conversationId" uuid, "status" "public"."rillo_moderation_cases_status_enum" NOT NULL DEFAULT 'open', "reportCount" integer NOT NULL DEFAULT '0', "lastReportedAt" TIMESTAMP, "reviewedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9d689fec3fdf3a82674e157a049" UNIQUE ("targetType", "postId", "conversationId"), CONSTRAINT "PK_bcc50f8690665bb98f422c4611d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2dd0d2c6853acc5fc2e14b1720" ON "rillo_moderation_cases" ("status", "lastReportedAt") `);
        await queryRunner.query(`CREATE TABLE "rillo_follows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "followerId" uuid NOT NULL, "followingId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe8951a7851078f3f6be2ae2c12" UNIQUE ("followerId", "followingId"), CONSTRAINT "PK_83419349a425b62c464d762fad1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7db96bb85e075d153a7e4b0a6" ON "rillo_follows" ("followingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_20529152c00a3bf2da9ecb3ed3" ON "rillo_follows" ("followerId") `);
        await queryRunner.query(`CREATE TABLE "rillo_file_references" ("id" SERIAL NOT NULL, "file_id" integer NOT NULL, "resource" character varying(50) NOT NULL, "resource_id" integer NOT NULL, "reference_type" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_770684fc06993cc3c3591269d7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_contact_contact_catagory_enum" AS ENUM('Bug Report', 'Feature Request', 'Account Issues', 'Feedback & Suggesttions', 'Partnership Inquiry', 'Payment & Billing', 'Other')`);
        await queryRunner.query(`CREATE TABLE "rillo_contact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contact_catagory" "public"."rillo_contact_contact_catagory_enum" NOT NULL DEFAULT 'Other', "remarks" character varying, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_37f26910cba3b134f3d114dd633" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_conversation_clear" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "cleared_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_ecf52a834df47dd1e6a955f977b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" text NOT NULL, "postId" uuid NOT NULL, "file_id" integer, "userId" uuid NOT NULL, "parentId" uuid, "likeCount" integer NOT NULL DEFAULT '0', "replyCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_bb3ea6042541ace0eec64fdc722" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f0e63dd401559ce88f2b646c6" ON "rillo_comments" ("postId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "rillo_comment_likes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "commentId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a54cc6a5d08beba50fcd6517513" UNIQUE ("commentId", "userId"), CONSTRAINT "PK_107fe6efb8790a5b9baf6b8b339" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_chat_requests_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'blocked', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "rillo_chat_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "receiver_id" uuid NOT NULL, "conversation_id" uuid, "status" "public"."rillo_chat_requests_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dfd5daf39283b0a35751612f4f5" UNIQUE ("sender_id", "receiver_id"), CONSTRAINT "PK_5325b69b8ec3ac7e22489d62a18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_user_chat_hide" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loggedInUserId" uuid NOT NULL, "targetUserId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "UQ_ba7ebed90d486bad326de9c4198" UNIQUE ("loggedInUserId", "targetUserId"), CONSTRAINT "PK_ba73e415c078f2d4b35750e63b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_message_status_enum" AS ENUM('sent', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "rillo_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "text" text NOT NULL, "reply_to_message_id" uuid, "status" "public"."rillo_message_status_enum" NOT NULL DEFAULT 'sent', "file_ids" integer array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1dadef9c700589edd59fc67494a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_conversation_read" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "last_read_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_fe7c1281c19201ae66a278a3828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_conversation_pins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_36294e2e7baa000df48cff01e82" UNIQUE ("conversation_id", "user_id"), CONSTRAINT "PK_d0f8f130d9be2dfafba3026d00a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_conversation_mute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "muted_until" TIMESTAMP, CONSTRAINT "PK_5965bf6262baa8ae47af6e93027" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_chat_report_criteria_criteria_enum" AS ENUM('TERRORISM', 'HARASSMENT', 'HATE_SPEECH', 'SPAM', 'IMPERSONATION', 'VIOLENCE')`);
        await queryRunner.query(`CREATE TABLE "rillo_chat_report_criteria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportId" uuid NOT NULL, "criteria" "public"."rillo_chat_report_criteria_criteria_enum" NOT NULL, CONSTRAINT "UQ_b8726a16d2e4c60a782a5066a42" UNIQUE ("reportId", "criteria"), CONSTRAINT "PK_05f851c1079b756de60816a0bdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_chat_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loggedInUserId" uuid NOT NULL, "conversationId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_eeed1bf8e0ce6481fe3fdd9020d" UNIQUE ("loggedInUserId", "conversationId"), CONSTRAINT "PK_bda7d25db1d6df53622d14aad27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_boost_package_benifits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "boost_package_id" uuid NOT NULL, "desc" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_77b21e860dc4ab9fe4f6e339d62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_boost_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "price" double precision NOT NULL DEFAULT '0', "discountPercentage" double precision DEFAULT '0', "discountPrice" double precision NOT NULL DEFAULT '0', "boostQuantity" integer NOT NULL DEFAULT '0', "type" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_9b8a5fa979c3fc6c4c0ef593339" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_boost_payment_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "boost_package_id" uuid NOT NULL, "post_id" uuid NOT NULL, "purchased_quantity" integer NOT NULL DEFAULT '0', "used_quantity" integer NOT NULL DEFAULT '0', "remaining_quantity" integer NOT NULL DEFAULT '0', "is_success" boolean NOT NULL DEFAULT false, "message" character varying(255), "validation_errors" jsonb, "invoice_id" bigint, "invoice_status" character varying(100), "invoice_reference" character varying(255), "customer_reference" character varying(255), "provider_created_at" TIMESTAMP, "expiry_date" date, "expiry_time" character varying(50), "invoice_value" double precision, "comments" text, "customer_name" character varying(255), "customer_mobile" character varying(50), "customer_email" character varying(255), "user_defined_field" character varying(255), "invoice_display_value" character varying(100), "due_deposit" double precision, "deposit_status" character varying(100), "invoice_items" jsonb, "invoice_transactions" jsonb, "suppliers" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f07f7ea888b9a40c5ae7c4804c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_post_boosts_status_enum" AS ENUM('active', 'expired', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "rillo_post_boosts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "post_id" uuid NOT NULL, "boost_package_id" uuid NOT NULL, "boost_payment_record_id" uuid NOT NULL, "boost_quantity" integer NOT NULL DEFAULT '0', "boost_minutes" integer NOT NULL DEFAULT '0', "starts_at" TIMESTAMP NOT NULL, "ends_at" TIMESTAMP NOT NULL, "status" "public"."rillo_post_boosts_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_80d56b7b279c2abd7f83b746e54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_audit_logs" ("id" SERIAL NOT NULL, "userId" character varying, "username" character varying(255), "action" character varying(50) NOT NULL, "resource" character varying(100) NOT NULL, "resourceId" character varying(100), "method" character varying(10) NOT NULL, "url" character varying(500) NOT NULL, "ip" character varying(45) NOT NULL, "userAgent" character varying(500) NOT NULL, "requestBody" json, "responseStatus" integer NOT NULL, "responseTime" integer NOT NULL, "success" boolean NOT NULL, "error" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_72ce025537bebcb818e3cc3f5e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_854fac021e960c960a30b7a306" ON "rillo_audit_logs" ("success", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b497577c273288a2b1f66697e" ON "rillo_audit_logs" ("action", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec7ed4bfc6c7a274fd972a8056" ON "rillo_audit_logs" ("resource", "resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_904c2b1f7cac53d4ce0936a76e" ON "rillo_audit_logs" ("userId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "rillo_refresh_tokens" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isRevoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_57f35a8a2629f828032dbb96e89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rillo_app_instructions_particulars_enum" AS ENUM('Distance levels in Rillo', 'Notes', 'Rillo modes')`);
        await queryRunner.query(`CREATE TABLE "rillo_app_instructions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "particulars" "public"."rillo_app_instructions_particulars_enum" NOT NULL DEFAULT 'Notes', "instruction" character varying NOT NULL, "sorting_no" integer DEFAULT '0', "created_by_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_fc6593d0c310ea1b1acdac96258" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rillo_password_reset_tokens" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "code" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isUsed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_4cc084930b47355f01ec832a6a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "rillo_files" ADD CONSTRAINT "FK_773e94d06ca230927883fd33b83" FOREIGN KEY ("uploaded_by") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_users" ADD CONSTRAINT "FK_ef4c2c19238df902deab1bf3f30" FOREIGN KEY ("file_id") REFERENCES "rillo_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_users_location" ADD CONSTRAINT "FK_21c838546367a3b13f732f1835a" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_subscription_package_benifits" ADD CONSTRAINT "FK_10616e3fddc1a89bbbb652786d4" FOREIGN KEY ("subscription_package_id") REFERENCES "rillo_subscription_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_delete_account" ADD CONSTRAINT "FK_ef0a499f30e45d2dbfb3087779d" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_story" ADD CONSTRAINT "FK_20421b07932288469f67bc475e5" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_story" ADD CONSTRAINT "FK_1168d19507069f0442e87944481" FOREIGN KEY ("file_id") REFERENCES "rillo_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_story_like" ADD CONSTRAINT "FK_9d70c94c8de4fcc75c76627dc73" FOREIGN KEY ("story_id") REFERENCES "rillo_story"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_story_view" ADD CONSTRAINT "FK_bfadfaad415d17a770534cb1fb4" FOREIGN KEY ("story_id") REFERENCES "rillo_story"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_stickers" ADD CONSTRAINT "FK_dcd44ecf97e2a60a58c04423797" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_stickers" ADD CONSTRAINT "FK_d4bf0028de3e8fd2ad4cb15a4bb" FOREIGN KEY ("file_id") REFERENCES "rillo_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_post_hide" ADD CONSTRAINT "FK_488143d970ef697e4300c3a2e85" FOREIGN KEY ("loggedInUserId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_post_hide" ADD CONSTRAINT "FK_7cadd87f71ceab4826fbae684e6" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_options" ADD CONSTRAINT "FK_e27a8587f8eb1aa10a5b32c5a19" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_files" ADD CONSTRAINT "FK_d384ca1340889816b5d3053ccc1" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_files" ADD CONSTRAINT "FK_ff04b03b0a84f555edc049f40e1" FOREIGN KEY ("fileId") REFERENCES "rillo_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_posts" ADD CONSTRAINT "FK_ba32cf92e4e5fed1cab7a954a95" FOREIGN KEY ("originalPostId") REFERENCES "rillo_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_posts" ADD CONSTRAINT "FK_af7c8858abfa901716b2cb299a7" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_reports" ADD CONSTRAINT "FK_fbc96bbedbdc2e9b77162dc973c" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_reports" ADD CONSTRAINT "FK_0cfa362c0643aa78d1e49a97589" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_report_criteria" ADD CONSTRAINT "FK_3d4e4afff759efd9b928d05293f" FOREIGN KEY ("reportId") REFERENCES "rillo_post_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_votes" ADD CONSTRAINT "FK_ee57a2c0afd6ed974b6436d0878" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_votes" ADD CONSTRAINT "FK_33c1efd53fee36e9afdfa140fd8" FOREIGN KEY ("postPollOptionId") REFERENCES "rillo_post_poll_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_votes" ADD CONSTRAINT "FK_720563730cc6e754ea768a4aa40" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_views" ADD CONSTRAINT "FK_e5abb891cb584f7e44186fabd30" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_pins" ADD CONSTRAINT "FK_31a0f5221f46e91a06ab1308657" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_notification" ADD CONSTRAINT "FK_e3bf19956572471dc5fedef3db8" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_notification" ADD CONSTRAINT "FK_335e6f0b1ab89025fa84eadc4ca" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_hide" ADD CONSTRAINT "FK_1fb37b051bc09193d90797b4cfe" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_hide" ADD CONSTRAINT "FK_e162a1fdc83f6fedcff872be9f9" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_likes" ADD CONSTRAINT "FK_01302b046f62a36bba9ca8e2b97" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_poll_options" ADD CONSTRAINT "FK_fcbd31ba25db44e2b7886f3d9b6" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_subscription_payments" ADD CONSTRAINT "FK_359ad5c65b75f309d21084342db" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_subscription_payments" ADD CONSTRAINT "FK_ed6a554566b667b0cc5e4828973" FOREIGN KEY ("subscription_package_id") REFERENCES "rillo_subscription_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_subscriptions" ADD CONSTRAINT "FK_aefa4198e0e544865d281656f2c" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_subscriptions" ADD CONSTRAINT "FK_697b89679c9a09811b0a2466425" FOREIGN KEY ("subscription_package_id") REFERENCES "rillo_subscription_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_subscriptions" ADD CONSTRAINT "FK_35738d36c00ac1862b636ed7741" FOREIGN KEY ("subscription_payment_id") REFERENCES "rillo_subscription_payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_to_firebase_token_map" ADD CONSTRAINT "FK_4239f73b322517e1b7b87f23d9c" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_payments_records" ADD CONSTRAINT "FK_594265469bf686546b7663907aa" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_payments_records" ADD CONSTRAINT "FK_1365a639a0a3ca3cfd902f4367e" FOREIGN KEY ("subscription_package_id") REFERENCES "rillo_subscription_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_notification_records" ADD CONSTRAINT "FK_6f62a8e3484b3cd76abe03684ed" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_requests" ADD CONSTRAINT "FK_d5ae3cafb78a7794dd66e4e3a84" FOREIGN KEY ("requestedById") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_requests" ADD CONSTRAINT "FK_9e4c89fccd5f9de15de790da9f0" FOREIGN KEY ("reviewedById") REFERENCES "rillo_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_actions" ADD CONSTRAINT "FK_459ec0feec4c8c7a58ec970e256" FOREIGN KEY ("caseId") REFERENCES "rillo_moderation_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_actions" ADD CONSTRAINT "FK_f03e956eb1696d0325ea59f0fbf" FOREIGN KEY ("moderatorUserId") REFERENCES "rillo_users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation_participant" ADD CONSTRAINT "FK_bb4b9ed2aba3da1e2ba214d1be5" FOREIGN KEY ("conversation_id") REFERENCES "rillo_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation_participant" ADD CONSTRAINT "FK_6bbd6a3d807277973551e1cc9c7" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation" ADD CONSTRAINT "FK_d14f2a8bf683d41e6688a518b84" FOREIGN KEY ("user_one_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation" ADD CONSTRAINT "FK_83798f58fb390fe015d1d5e97d5" FOREIGN KEY ("image_id") REFERENCES "rillo_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation" ADD CONSTRAINT "FK_52087f8a374998083a96a2ef072" FOREIGN KEY ("user_two_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_cases" ADD CONSTRAINT "FK_582ca0235797ed21b7242303242" FOREIGN KEY ("postId") REFERENCES "rillo_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_cases" ADD CONSTRAINT "FK_6472757e29d7ae2e08385711a91" FOREIGN KEY ("conversationId") REFERENCES "rillo_conversation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_file_references" ADD CONSTRAINT "FK_3ef86bb37822f7f87249d460d47" FOREIGN KEY ("file_id") REFERENCES "rillo_files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_contact" ADD CONSTRAINT "FK_0bf769ebbbb8f63dbbda0997057" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_comments" ADD CONSTRAINT "FK_3add13e94aede81f7c7a474a866" FOREIGN KEY ("parentId") REFERENCES "rillo_comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_comments" ADD CONSTRAINT "FK_595eaa757d709de514496807f11" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_comments" ADD CONSTRAINT "FK_67d30b7a56e0875f225f80f3140" FOREIGN KEY ("file_id") REFERENCES "rillo_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_comment_likes" ADD CONSTRAINT "FK_344b0dc69ec5e035ee0bf294a16" FOREIGN KEY ("commentId") REFERENCES "rillo_comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_requests" ADD CONSTRAINT "FK_0ac655f6366f5dbe31d0e46f90f" FOREIGN KEY ("sender_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_requests" ADD CONSTRAINT "FK_b0912c224645f497b2e542b5edf" FOREIGN KEY ("receiver_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_chat_hide" ADD CONSTRAINT "FK_c96dafa177d9e4a39deb5106662" FOREIGN KEY ("loggedInUserId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_user_chat_hide" ADD CONSTRAINT "FK_5dc6e340eefa88b3f4d3ff748a8" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_message" ADD CONSTRAINT "FK_08a848475c500aacc26cfb2a4d6" FOREIGN KEY ("sender_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation_pins" ADD CONSTRAINT "FK_4fbbf6fcd9f95186b53108ee408" FOREIGN KEY ("conversation_id") REFERENCES "rillo_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_report_criteria" ADD CONSTRAINT "FK_06f183130bb2e355f64f01435d5" FOREIGN KEY ("reportId") REFERENCES "rillo_chat_reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_reports" ADD CONSTRAINT "FK_0f836dd160b8e68274329436e34" FOREIGN KEY ("loggedInUserId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_reports" ADD CONSTRAINT "FK_709e3106bde2763bd6be55f2413" FOREIGN KEY ("conversationId") REFERENCES "rillo_conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_package_benifits" ADD CONSTRAINT "FK_98d1bf9a2faf8bb7db7bfe9e8db" FOREIGN KEY ("boost_package_id") REFERENCES "rillo_boost_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_payment_records" ADD CONSTRAINT "FK_6565cffaa857b1f54518b64cb47" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_payment_records" ADD CONSTRAINT "FK_0d207266e8a64678f493da57be0" FOREIGN KEY ("boost_package_id") REFERENCES "rillo_boost_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_payment_records" ADD CONSTRAINT "FK_58f51ef0d363db9f21017e24eed" FOREIGN KEY ("post_id") REFERENCES "rillo_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" ADD CONSTRAINT "FK_dea307b661a95da2cf7d00eea74" FOREIGN KEY ("user_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" ADD CONSTRAINT "FK_66fd9570267af5780e4becf21c7" FOREIGN KEY ("post_id") REFERENCES "rillo_posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" ADD CONSTRAINT "FK_3a9bb6addec37e4e5aa14acdcb8" FOREIGN KEY ("boost_package_id") REFERENCES "rillo_boost_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" ADD CONSTRAINT "FK_64065554c093c94e7e16d3f878c" FOREIGN KEY ("boost_payment_record_id") REFERENCES "rillo_boost_payment_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_refresh_tokens" ADD CONSTRAINT "FK_acee0f359e3d84d298de863d58a" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_app_instructions" ADD CONSTRAINT "FK_622aa56eaf50713641d3a410bba" FOREIGN KEY ("created_by_id") REFERENCES "rillo_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rillo_password_reset_tokens" ADD CONSTRAINT "FK_5d54e98baf142dcf5c3f71e21b8" FOREIGN KEY ("userId") REFERENCES "rillo_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rillo_password_reset_tokens" DROP CONSTRAINT "FK_5d54e98baf142dcf5c3f71e21b8"`);
        await queryRunner.query(`ALTER TABLE "rillo_app_instructions" DROP CONSTRAINT "FK_622aa56eaf50713641d3a410bba"`);
        await queryRunner.query(`ALTER TABLE "rillo_refresh_tokens" DROP CONSTRAINT "FK_acee0f359e3d84d298de863d58a"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" DROP CONSTRAINT "FK_64065554c093c94e7e16d3f878c"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" DROP CONSTRAINT "FK_3a9bb6addec37e4e5aa14acdcb8"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" DROP CONSTRAINT "FK_66fd9570267af5780e4becf21c7"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_boosts" DROP CONSTRAINT "FK_dea307b661a95da2cf7d00eea74"`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_payment_records" DROP CONSTRAINT "FK_58f51ef0d363db9f21017e24eed"`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_payment_records" DROP CONSTRAINT "FK_0d207266e8a64678f493da57be0"`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_payment_records" DROP CONSTRAINT "FK_6565cffaa857b1f54518b64cb47"`);
        await queryRunner.query(`ALTER TABLE "rillo_boost_package_benifits" DROP CONSTRAINT "FK_98d1bf9a2faf8bb7db7bfe9e8db"`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_reports" DROP CONSTRAINT "FK_709e3106bde2763bd6be55f2413"`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_reports" DROP CONSTRAINT "FK_0f836dd160b8e68274329436e34"`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_report_criteria" DROP CONSTRAINT "FK_06f183130bb2e355f64f01435d5"`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation_pins" DROP CONSTRAINT "FK_4fbbf6fcd9f95186b53108ee408"`);
        await queryRunner.query(`ALTER TABLE "rillo_message" DROP CONSTRAINT "FK_08a848475c500aacc26cfb2a4d6"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_chat_hide" DROP CONSTRAINT "FK_5dc6e340eefa88b3f4d3ff748a8"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_chat_hide" DROP CONSTRAINT "FK_c96dafa177d9e4a39deb5106662"`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_requests" DROP CONSTRAINT "FK_b0912c224645f497b2e542b5edf"`);
        await queryRunner.query(`ALTER TABLE "rillo_chat_requests" DROP CONSTRAINT "FK_0ac655f6366f5dbe31d0e46f90f"`);
        await queryRunner.query(`ALTER TABLE "rillo_comment_likes" DROP CONSTRAINT "FK_344b0dc69ec5e035ee0bf294a16"`);
        await queryRunner.query(`ALTER TABLE "rillo_comments" DROP CONSTRAINT "FK_67d30b7a56e0875f225f80f3140"`);
        await queryRunner.query(`ALTER TABLE "rillo_comments" DROP CONSTRAINT "FK_595eaa757d709de514496807f11"`);
        await queryRunner.query(`ALTER TABLE "rillo_comments" DROP CONSTRAINT "FK_3add13e94aede81f7c7a474a866"`);
        await queryRunner.query(`ALTER TABLE "rillo_contact" DROP CONSTRAINT "FK_0bf769ebbbb8f63dbbda0997057"`);
        await queryRunner.query(`ALTER TABLE "rillo_file_references" DROP CONSTRAINT "FK_3ef86bb37822f7f87249d460d47"`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_cases" DROP CONSTRAINT "FK_6472757e29d7ae2e08385711a91"`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_cases" DROP CONSTRAINT "FK_582ca0235797ed21b7242303242"`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation" DROP CONSTRAINT "FK_52087f8a374998083a96a2ef072"`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation" DROP CONSTRAINT "FK_83798f58fb390fe015d1d5e97d5"`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation" DROP CONSTRAINT "FK_d14f2a8bf683d41e6688a518b84"`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation_participant" DROP CONSTRAINT "FK_6bbd6a3d807277973551e1cc9c7"`);
        await queryRunner.query(`ALTER TABLE "rillo_conversation_participant" DROP CONSTRAINT "FK_bb4b9ed2aba3da1e2ba214d1be5"`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_actions" DROP CONSTRAINT "FK_f03e956eb1696d0325ea59f0fbf"`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_actions" DROP CONSTRAINT "FK_459ec0feec4c8c7a58ec970e256"`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_requests" DROP CONSTRAINT "FK_9e4c89fccd5f9de15de790da9f0"`);
        await queryRunner.query(`ALTER TABLE "rillo_moderation_requests" DROP CONSTRAINT "FK_d5ae3cafb78a7794dd66e4e3a84"`);
        await queryRunner.query(`ALTER TABLE "rillo_notification_records" DROP CONSTRAINT "FK_6f62a8e3484b3cd76abe03684ed"`);
        await queryRunner.query(`ALTER TABLE "rillo_payments_records" DROP CONSTRAINT "FK_1365a639a0a3ca3cfd902f4367e"`);
        await queryRunner.query(`ALTER TABLE "rillo_payments_records" DROP CONSTRAINT "FK_594265469bf686546b7663907aa"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_to_firebase_token_map" DROP CONSTRAINT "FK_4239f73b322517e1b7b87f23d9c"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_subscriptions" DROP CONSTRAINT "FK_35738d36c00ac1862b636ed7741"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_subscriptions" DROP CONSTRAINT "FK_697b89679c9a09811b0a2466425"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_subscriptions" DROP CONSTRAINT "FK_aefa4198e0e544865d281656f2c"`);
        await queryRunner.query(`ALTER TABLE "rillo_subscription_payments" DROP CONSTRAINT "FK_ed6a554566b667b0cc5e4828973"`);
        await queryRunner.query(`ALTER TABLE "rillo_subscription_payments" DROP CONSTRAINT "FK_359ad5c65b75f309d21084342db"`);
        await queryRunner.query(`ALTER TABLE "rillo_poll_options" DROP CONSTRAINT "FK_fcbd31ba25db44e2b7886f3d9b6"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_likes" DROP CONSTRAINT "FK_01302b046f62a36bba9ca8e2b97"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_hide" DROP CONSTRAINT "FK_e162a1fdc83f6fedcff872be9f9"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_hide" DROP CONSTRAINT "FK_1fb37b051bc09193d90797b4cfe"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_notification" DROP CONSTRAINT "FK_335e6f0b1ab89025fa84eadc4ca"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_notification" DROP CONSTRAINT "FK_e3bf19956572471dc5fedef3db8"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_pins" DROP CONSTRAINT "FK_31a0f5221f46e91a06ab1308657"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_views" DROP CONSTRAINT "FK_e5abb891cb584f7e44186fabd30"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_votes" DROP CONSTRAINT "FK_720563730cc6e754ea768a4aa40"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_votes" DROP CONSTRAINT "FK_33c1efd53fee36e9afdfa140fd8"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_votes" DROP CONSTRAINT "FK_ee57a2c0afd6ed974b6436d0878"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_report_criteria" DROP CONSTRAINT "FK_3d4e4afff759efd9b928d05293f"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_reports" DROP CONSTRAINT "FK_0cfa362c0643aa78d1e49a97589"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_reports" DROP CONSTRAINT "FK_fbc96bbedbdc2e9b77162dc973c"`);
        await queryRunner.query(`ALTER TABLE "rillo_posts" DROP CONSTRAINT "FK_af7c8858abfa901716b2cb299a7"`);
        await queryRunner.query(`ALTER TABLE "rillo_posts" DROP CONSTRAINT "FK_ba32cf92e4e5fed1cab7a954a95"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_files" DROP CONSTRAINT "FK_ff04b03b0a84f555edc049f40e1"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_files" DROP CONSTRAINT "FK_d384ca1340889816b5d3053ccc1"`);
        await queryRunner.query(`ALTER TABLE "rillo_post_poll_options" DROP CONSTRAINT "FK_e27a8587f8eb1aa10a5b32c5a19"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_post_hide" DROP CONSTRAINT "FK_7cadd87f71ceab4826fbae684e6"`);
        await queryRunner.query(`ALTER TABLE "rillo_user_post_hide" DROP CONSTRAINT "FK_488143d970ef697e4300c3a2e85"`);
        await queryRunner.query(`ALTER TABLE "rillo_stickers" DROP CONSTRAINT "FK_d4bf0028de3e8fd2ad4cb15a4bb"`);
        await queryRunner.query(`ALTER TABLE "rillo_stickers" DROP CONSTRAINT "FK_dcd44ecf97e2a60a58c04423797"`);
        await queryRunner.query(`ALTER TABLE "rillo_story_view" DROP CONSTRAINT "FK_bfadfaad415d17a770534cb1fb4"`);
        await queryRunner.query(`ALTER TABLE "rillo_story_like" DROP CONSTRAINT "FK_9d70c94c8de4fcc75c76627dc73"`);
        await queryRunner.query(`ALTER TABLE "rillo_story" DROP CONSTRAINT "FK_1168d19507069f0442e87944481"`);
        await queryRunner.query(`ALTER TABLE "rillo_story" DROP CONSTRAINT "FK_20421b07932288469f67bc475e5"`);
        await queryRunner.query(`ALTER TABLE "rillo_delete_account" DROP CONSTRAINT "FK_ef0a499f30e45d2dbfb3087779d"`);
        await queryRunner.query(`ALTER TABLE "rillo_subscription_package_benifits" DROP CONSTRAINT "FK_10616e3fddc1a89bbbb652786d4"`);
        await queryRunner.query(`ALTER TABLE "rillo_users_location" DROP CONSTRAINT "FK_21c838546367a3b13f732f1835a"`);
        await queryRunner.query(`ALTER TABLE "rillo_users" DROP CONSTRAINT "FK_ef4c2c19238df902deab1bf3f30"`);
        await queryRunner.query(`ALTER TABLE "rillo_files" DROP CONSTRAINT "FK_773e94d06ca230927883fd33b83"`);
        await queryRunner.query(`DROP TABLE "rillo_password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "rillo_app_instructions"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_app_instructions_particulars_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_904c2b1f7cac53d4ce0936a76e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec7ed4bfc6c7a274fd972a8056"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b497577c273288a2b1f66697e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_854fac021e960c960a30b7a306"`);
        await queryRunner.query(`DROP TABLE "rillo_audit_logs"`);
        await queryRunner.query(`DROP TABLE "rillo_post_boosts"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_post_boosts_status_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_boost_payment_records"`);
        await queryRunner.query(`DROP TABLE "rillo_boost_packages"`);
        await queryRunner.query(`DROP TABLE "rillo_boost_package_benifits"`);
        await queryRunner.query(`DROP TABLE "rillo_chat_reports"`);
        await queryRunner.query(`DROP TABLE "rillo_chat_report_criteria"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_chat_report_criteria_criteria_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_conversation_mute"`);
        await queryRunner.query(`DROP TABLE "rillo_conversation_pins"`);
        await queryRunner.query(`DROP TABLE "rillo_conversation_read"`);
        await queryRunner.query(`DROP TABLE "rillo_message"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_message_status_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_user_chat_hide"`);
        await queryRunner.query(`DROP TABLE "rillo_chat_requests"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_chat_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_comment_likes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f0e63dd401559ce88f2b646c6"`);
        await queryRunner.query(`DROP TABLE "rillo_comments"`);
        await queryRunner.query(`DROP TABLE "rillo_conversation_clear"`);
        await queryRunner.query(`DROP TABLE "rillo_contact"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_contact_contact_catagory_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_file_references"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20529152c00a3bf2da9ecb3ed3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7db96bb85e075d153a7e4b0a6"`);
        await queryRunner.query(`DROP TABLE "rillo_follows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dd0d2c6853acc5fc2e14b1720"`);
        await queryRunner.query(`DROP TABLE "rillo_moderation_cases"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_moderation_cases_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_moderation_cases_targettype_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_conversation"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_conversation_type_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_conversation_participant"`);
        await queryRunner.query(`DROP TABLE "rillo_moderation_actions"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_moderation_actions_actiontype_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_moderation_requests"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_moderation_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_notification_records"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_notification_records_deliverystatus_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_payments_records"`);
        await queryRunner.query(`DROP TABLE "rillo_user_to_firebase_token_map"`);
        await queryRunner.query(`DROP TABLE "rillo_user_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_user_subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_subscription_payments"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_subscription_payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_poll_options"`);
        await queryRunner.query(`DROP TABLE "rillo_post_likes"`);
        await queryRunner.query(`DROP TABLE "rillo_post_hide"`);
        await queryRunner.query(`DROP TABLE "rillo_post_notification"`);
        await queryRunner.query(`DROP TABLE "rillo_post_pins"`);
        await queryRunner.query(`DROP TABLE "rillo_post_views"`);
        await queryRunner.query(`DROP TABLE "rillo_post_poll_votes"`);
        await queryRunner.query(`DROP TABLE "rillo_post_report_criteria"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_post_report_criteria_criteria_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_post_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de071e5e776235cc5dca2eb304"`);
        await queryRunner.query(`DROP TABLE "rillo_posts"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_posts_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_posts_posttype_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_post_files"`);
        await queryRunner.query(`DROP TABLE "rillo_post_poll_options"`);
        await queryRunner.query(`DROP TABLE "rillo_user_post_hide"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcd44ecf97e2a60a58c0442379"`);
        await queryRunner.query(`DROP TABLE "rillo_stickers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8ce692b12a551825561f21532"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfadfaad415d17a770534cb1fb"`);
        await queryRunner.query(`DROP TABLE "rillo_story_view"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05776324cabb03bab023d7167b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d70c94c8de4fcc75c76627dc7"`);
        await queryRunner.query(`DROP TABLE "rillo_story_like"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20421b07932288469f67bc475e"`);
        await queryRunner.query(`DROP TABLE "rillo_story"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_story_visibility_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_delete_account"`);
        await queryRunner.query(`DROP TABLE "rillo_subscription_packages"`);
        await queryRunner.query(`DROP TABLE "rillo_subscription_package_benifits"`);
        await queryRunner.query(`DROP INDEX "public"."idx_userlocation_location"`);
        await queryRunner.query(`DROP INDEX "public"."idx_userlocation_user_id"`);
        await queryRunner.query(`DROP TABLE "rillo_users_location"`);
        await queryRunner.query(`DROP TABLE "rillo_users"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_users_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_users_gender_enum"`);
        await queryRunner.query(`DROP TABLE "rillo_files"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_files_file_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rillo_files_file_type_enum"`);
    }

}
